### ISSUE TITLE
MySQL Error on Startup

### ISSUE THREAD

**Issue by Lucraft** [QuiltServerTools/Ledger-Databases#11]
Tried to set up Ledger with MySQL, but upon starting the server I get this error:

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-11-22 22:27:54
Description: Exception in server tick loop

java.sql.SQLSyntaxErrorException: Unknown column 'RESERVED' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getSQLKeywords(DatabaseMetaDataUsingInfoSchema.java:1178)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcIdentifierManager.<init>(JdbcIdentifierManager.kt:14)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$identifierManager$2.invoke(JdbcDatabaseMetadataImpl.kt:60)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$identifierManager$2.invoke(JdbcDatabaseMetadataImpl.kt:58)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$lazyMetadata$1.invoke(JdbcDatabaseMetadataImpl.kt:257)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getIdentifierManager(JdbcDatabaseMetadataImpl.kt:58)
	at org.jetbrains.exposed.sql.Database$identifierManager$2$1.invoke(Database.kt:59)
	at org.jetbrains.exposed.sql.Database$identifierManager$2$1.invoke(Database.kt:59)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:63)
	at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:39)
	at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:59)
	at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:59)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:59)
	at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:163)
	at org.jetbrains.exposed.sql.Table.createStatement(Table.kt:1085)
	at org.jetbrains.exposed.sql.Table.getDdl(Table.kt:1056)
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:99)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:310)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:306)
	at com.github.quiltservertools.ledger.database.DatabaseManager$ensureTables$1.invoke(DatabaseManager.kt:95)
	at com.github.quiltservertools.ledger.database.DatabaseManager$ensureTables$1.invoke(DatabaseManager.kt:94)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131)
	at com.github.quiltservertools.ledger.database.DatabaseManager.ensureTables(DatabaseManager.kt:94)
	at com.github.quiltservertools.ledger.Ledger.serverStarting(Ledger.kt:74)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
	at net.minecraft.server.MinecraftServer.handler$zmm000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:3337)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-88-generic
	Java Version: 17.0.9, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 820128616 bytes (782 MiB) / 1652555776 bytes (1576 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7402P 24-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12013.93
	Virtual memory used (MB): 7150.18
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms128M -Xmx8000M
	Fabric Mods: 
		architectury: Architectury 9.1.12
		automodpack: AutoModpack 3.5.2
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			pl_skidam_automodpack_core-fabric_: core-fabric 3.5.2
			pl_skidam_automodpack_server-host_: server-host 3.5.2
			preloading_tricks: Preloading Tricks 0.0.14
				preloading_tricks_language_adapter: Preloading Tricks Dummy Language Adapter 0.0.14
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.4
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		carpeted: Carpeted 1.20-1.4
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		create: Create 0.5.1-d-build.5+mc1.20.1
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		creaturesfromthesnow: Creatures from The Snow [1.20] 6.0.0
		delightfulcreators: Delightful Creators 1.1.8
		everycomp: Every Compat 1.20-2.6.17
		fabric-api: Fabric API 0.90.7+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.12+kotlin.1.9.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.24
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		java: OpenJDK 64-Bit Server VM 17
		ledger: Ledger 1.2.8
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		ledger-databases: Ledger Databases 1.1.1
			com_h2database_h2: h2 1.4.200
			mysql_mysql-connector-java: mysql-connector-java 8.0.19
			org_postgresql_postgresql: postgresql 42.3.0
		lithium: Lithium 0.11.2
		lovely_snails: Lovely Snails 1.1.3+1.20.1
		mcdiscordchat: MC-Discord-Chat 2.2.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.14.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.14.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.14.1
			com_google_code_gson_gson: gson 2.10.1
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			com_squareup_okhttp3_okhttp: okhttp 4.11.0
			com_squareup_okio_okio: okio 2.10.0
			com_vdurmont_emoji-java: emoji-java 5.1.1
			mcdiscordchat-1_20_1: MC-Discord-Chat 2.2.3
			net_dv8tion_jda: JDA 5.0.0-beta.16
			net_sf_trove4j_trove4j: trove4j 3.0.3
			org_apache_commons_commons-collections4: commons-collections4 4.4
			org_json_json: json 20231013
			org_slf4j_slf4j-api: slf4j-api 2.0.7
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.8.65
			com_github_llamalad7_mixinextras: MixinExtras 0.2.1-beta.2
		mr_create_modtrims: Create mod Trims 1.0.0
		mysticaloaktree: Mystical Oak Tree 1.20-1.11
		mythicupgrades: Mythic Upgrades 2.3.2+mc1.20.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		reinfbarrel: Reinforced Barrels 2.4.1+1.20
		reinfchest: Reinforced Chests 2.4.2+1.20
		reinfshulker: Reinforced Shulker Boxes 2.5.0+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		roughlyenoughitems: Roughly Enough Items 12.0.674
			error_notifier: Error Notifier 1.0.9
		simpletrims: Simple Trims 0.2.0
		snowyspirit: Snowy Spirit 1.20-2.2.6
		supplementaries: Supplementaries 1.20-2.6.30
			mixinsquared: MixinSquared 0.1.1
		toms_storage: Tom's Simple Storage Mod 1.6.5
		trimmable_tools: Trimmable Tools 1.0.4
		trinkets: Trinkets 3.7.1
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		voicechat: Simple Voice Chat 1.20.1-2.4.28
		winterly: Winterly 0.9.3+1.20
			cardinal-components-world: Cardinal Components API (worlds) 5.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Data Packs: vanilla, Everycomp Generated Pack, Snowyspirit Generated Pack, Supplementaries Generated Pack, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by arvitus** [comment]
It seems like this was fixed in #13 but there is no release including that change yet. Would be nice if we could get that. At least here on github, at best also on modrinth :)

**Comment by BasToTheMax** [comment]
same error here.
Sadly can't update as I'm running minecraft 1.21.9
