### ISSUE TITLE
1.19 compatibility

### ISSUE THREAD

**Issue by dmunozv04** [QuiltServerTools/Ledger-Databases#5]
When launching 1.19 with the database extension, the console outputs this error message:
```[14:04:01] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.7
[14:04:02] [main/WARN]: Mod resolution failed
[14:04:02] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED ledger-databases 1.1.0 {depends minecraft @ [1.18.x]}, ROOT_FORCELOAD_SINGLE ledger-databases 1.1.0]
[14:04:02] [main/INFO]: Reason: [HARD_DEP ledger-databases 1.1.0 {depends minecraft @ [1.18.x]}]
[14:04:02] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-textures-v0, fabric-models-v0, fabric-screen-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[14:04:02] [main/INFO]: Fix: add [], remove [], replace [[ledger-databases 1.1.0] -> add:ledger-databases 1 ([(-∞,∞)])]
[14:04:02] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Ledger Databases' (ledger-databases) 1.1.0 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Ledger Databases' (ledger-databases) 1.1.0 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19-loader.0.14.7-launcher.0.11.0.jar:0.11.0]```

**Comment by dmunozv04** [comment]
Fixed on #4
